/**
 * TODO
 */
public enum RandomWord {
  ALFAROMEO, ASTONMARTIN, AUDI, BMW, BUGATTI, BUICK, CADILLAC, CHEVROLET, CHRYSLER, CITROEN, DODGE,
  FERRARI, FORD, FIAT, HONDA, HUMMER, HYUNDAI, INFINITI, ISUZU, JAGUAR, JEEP, KIA, LAMBORGHINI,
  LANDROVER, LEXUS, LINCOLN, LOTUS, MAZDA,MCLAREN, MERCEDES, MERCURY, MITSUBISHI, NISSAN,
  OLDSMOBILE, PAGANI, PEUGEOT, PONTIAC, PORSCHE, REGAL, RENAULT, SAAB, SATURN, SUBARU, SUZUKI,
  TOYOTA, TESLA, VOLKSWAGEN, VOLVO
}
